#!/usr/bin/env bash

echo "Creating bucket ... "
if [ "$#" -ne 1 ]; then
    echo "Usage: $0"
    exit 1
fi

aws s3api create-bucket --bucket $1 --region ap-south-1 --create-bucket-configuration LocationConstraint=ap-south-1